[versions]
org-springframework-boot = '4.0.0'
io-spring-javaformat = '0.0.45'
net-sourceforge-pmd = '7.18.0'
com-baomidou-mybatis-plus = '3.5.15'
org-mapstruct-mapstruct = "1.6.3"
org-apache-fesod = "1.3.0"

[libraries]
spring-boot-dependencies = { module = 'org.springframework.boot:spring-boot-dependencies', version.ref = 'org-springframework-boot' }
com-baomidou-mybatis-plus-bom = { module = 'com.baomidou:mybatis-plus-bom', version.ref = 'com-baomidou-mybatis-plus' }
# https://mvnrepository.com/artifact/org.mockito/mockito-core
org-mockito-mockito-core = 'org.mockito:mockito-core:5.18.0'
# https://mvnrepository.com/artifact/org.zalando/logbook-spring-boot-starter
org-zalando-logbook-spring-boot-starter = 'org.zalando:logbook-spring-boot-starter:3.12.3'
org-mapstruct-mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'org-mapstruct-mapstruct' }
org-mapstruct-mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'org-mapstruct-mapstruct' }
org-apache-fesod-fesod = { module = 'org.apache.fesod:fesod', version.ref = 'org-apache-fesod' }


# buildSrc dependencies
org-springframework-boot-gradle-plugin = { module = 'org.springframework.boot:spring-boot-gradle-plugin', version.ref = 'org-springframework-boot' }
io-spring-javaformat-spring-javaformat-checkstyle = { module = 'io.spring.javaformat:spring-javaformat-checkstyle', version.ref = 'io-spring-javaformat' }
io-spring-javaformat-spring-javaformat-gradle-plugin = { module = 'io.spring.javaformat:spring-javaformat-gradle-plugin', version.ref = 'io-spring-javaformat' }
net-sourceforge-pmd-pmd-ant = { module = 'net.sourceforge.pmd:pmd-ant', version.ref = 'net-sourceforge-pmd' }
net-sourceforge-pmd-pmd-java = { module = 'net.sourceforge.pmd:pmd-java', version.ref = 'net-sourceforge-pmd' }
